Repository GEOS-ESM/FVdycoreCubed_GridComp, pull requests merged in 2019-10, with the labels that each got.

#9 Initialize uc and vc to 0d0 in computeMassFluxesR8
  FV_StateMod.F90
Labels: 0 diff

#15 Fixes #5. Rename GFDL_fms to fms
  CMakeLists.txt
Labels: 0 diff structural

#17 Pull master into develop
  FV_StateMod.F90
Labels: 0 diff

#18 Merge develop into master
  CMakeLists.txt
Labels: 0 diff structural

#19 Update Externals for renamed FMS fvdycore
  Externals.cfg
Labels: 0 diff structural

#20 Merge develop into master
  Externals.cfg
Labels: 0 diff structural

#24 Hand merge master into dev/MAPL-2.0
  AdvCore_GridCompMod.F90
  CMakeLists.txt
  FV_StateMod.F90
Labels: 0 diff

#25 Register grids in advcore
  AdvCore_GridCompMod.F90
Labels: 0 diff structural

#22 Fix standalone dynadv driver
  DynCore_GridCompMod.F90
  StandAlone_DynAdvCore_GridCompMod.F90
Labels: 0 diff, bug

#29 Merge develop into master
  DynCore_GridCompMod.F90
  StandAlone_DynAdvCore_GridCompMod.F90
Labels: 0 diff trivial, enhancement

#28 Cvs to git updates handmerge
  DynCore_GridCompMod.F90
  FV_StateMod.F90
Labels: 0 diff

#30 Merge develop into Master
  DynCore_GridCompMod.F90
  FV_StateMod.F90
Labels: 0 diff

#31 Convert _VERIFY and _RETURN to VERIFY_ and RETURN_
  AdvCore_GridCompMod.F90
  AppGridCreate.F90
  CreateInterpWeights_GridCompMod.F90
  CubeToLatLon.F90
  DynCore_GridCompMod.F90
  FV_StateMod.F90
  StandAlone_DynAdvCore_GridCompMod.F90
  c2c.F90
  c2c_rst.F90
  interp_restarts.F90
Labels: 0 diff trivial

#33 Merge develop into dev/MAPL-2.0
  DynCore_GridCompMod.F90
  FV_StateMod.F90
  StandAlone_DynAdvCore_GridCompMod.F90
Labels: 0 diff
