Repository GEOS-ESM/FVdycoreCubed_GridComp, pull requests merged in 2021-11, with the labels that each got.

#139 Add automatic PR for develop to MAPL3 branch
  .github/PULL_REQUEST_TEMPLATE/auto_pr_to_mapl3.md
  .github/workflows/push-to-develop.yml
Labels: 0 diff structural

#142 Fix up CI names
  .circleci/config.yml
Labels: 0 diff

#141 MAPL V3 FLAP usage simplification
  .circleci/config.yml
  StandAlone_AdvCore.F90
  StandAlone_DynAdvCore.F90
  StandAlone_FV3_Dycore.F90
Labels: 0 diff trivial, MAPL3
