Repository GEOS-ESM/FVdycoreCubed_GridComp, pull requests merged in 2021-04, with the labels that each got.

#101 Change setup scripts depending on HYDROSTATIC build
  scripts/CMakeLists.txt
  scripts/fv3_setup
Labels: 0 diff

#102 Merge Develop into main for release
  scripts/CMakeLists.txt
  scripts/fv3_setup
Labels: 0 diff, 0 diff structural

#103 Update CI image to 6.1.0
  .circleci/config.yml
Labels: 0 diff trivial

#104 Merge main into develop
  .circleci/config.yml
Labels: 0 diff trivial

#98 Use GFE Namespace
  CMakeLists.txt
Labels: 0 diff

#97 Add support for Rome at NAS
  scripts/fv3.j
  scripts/fv3_setup
Labels: 0 diff trivial

#106 Merge Develop into main for Release
  CMakeLists.txt
  scripts/fv3.j
  scripts/fv3_setup
Labels: 0 diff

#107 Add CONTRIBUTING and CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: 0 diff trivial

#109 Fix misspelling in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 0 diff trivial

#108 Modified conditional statements to access AdvCore EXPORT pointers only when needed
  AdvCore_GridCompMod.F90
Labels: 0 diff
